### ISSUE TITLE
Stuck on "Downloading data and converting to GPX"

### ISSUE THREAD

**Issue by MKien** [vertongen/withings-gpx#11]
The exporter loads my activities, but when I choose one to export gets stuck on the "Downloading data and converting to GPX" message. 

This started happening for me on 9/13/19.

**Comment by svirpulis** [comment]
Hello!

I have the same problem. I'm using MacOS (Big Sur) and am stuck on "Stuck on "Downloading data and converting to GPX" Did you solve it and how?

**Comment by MKien** [comment]
Oh man that was a long time ago. Withings actually just syncs with Strava now, for me.On Mar 21, 2021 1:28 AM, svirpulis ***@***.***> wrote:
Hello!
I have the same problem. I'm using MacOS (Big Sur) and am stuck on "Stuck on "Downloading data and converting to GPX" Did you solve it and how?

**Comment by svirpulis** [comment]
Thanks for answer. Yes, but it synced incorrectly (lost most part of my distance) and I wanted to replace that workout, but I can't export it properly. :(
