### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by deadlyhifi** [vertongen/withings-gpx#12]
Looking at the Withings API - https://developer.withings.com/oauth2/ - the methods being used here aren't listed. Is this using an older API, or am I missing something?

**Comment by vertongen** [comment]
The document API doesn't contain all the information. 
I used the private API, the one the app uses to fetch all the data.

**Comment by deadlyhifi** [comment]
Interesting - is that private API documented anywhere?

I’m asking this because I want to build a PWA, so I can install it on my phone, and press a button to send straight to Strava.

**Comment by vertongen** [comment]
Great idea! 
I don't know any documentation of that private API. 
So I had to make some assumptions to get the right data, but it seems to work out for everyone.

**Comment by deadlyhifi** [comment]
Good job I didn’t get too far with it! https://support.withings.com/hc/en-us/articles/360036851114-Partner-Apps-What-is-Strava-
