### ISSUE TITLE
Save path of output directory of last exported files

### ISSUE THREAD

**Issue by lestard** [vertongen/withings-gpx#6]
First of all: Thanks for this app. It helps me a lot.

Would be great to save the selected path when a file is exported so that the next time you don't have to select the path again and again.

I'm happy to send a PR for this.

**Comment by vertongen** [comment]
great suggestion! If you have time to make a PR, feel free to do so and I'll include it in a release.

**Comment by vertongen** [comment]
One thought: where would you store that 'preference' ? 
Right now the keychain is the only 'storage' the program uses, which is dedicated to the credentials of the user. So it would have to be another place?

**Comment by lestard** [comment]
Good point. I've just thought "save it the same way as the credentials" but you are correct. The keychain isn't the correct place to do it. 

I don't know what the correct solution would be. In linux I know that many programs create a `.programm-name` folder in the users home and store their configs there. On mac-os some programs also do this but I don't know if this is the real way of doing it. In windows you might use also use the registry.

Is there some abstraction/API from electron for storing preferences?

**Comment by vertongen** [comment]
My suggestion would be to use a library to store data, something like this: https://github.com/electron-userland/electron-json-storage 
Or it can be another one if you have other suggestions.
