### ISSUE TITLE
Let users select 'startdate' and 'enddate' to load items

### ISSUE THREAD

**Issue by lestard** [vertongen/withings-gpx#7]
At the moment it loads only those items within the last 30 days. In the code it looks like it's possible to load items by specific start and enddate. It's just the UI missing for users to select these values. 

It's kind of connected to #3. While "load more" would do a good job for 90% of usages, if you wan't to load some specific items from a long time ago It might be awkward to press "load more" 20 times. In these cases selecting a specific start and enddate would be better.
I'm happy to send a PR for this if you think it's a good addition.

**Comment by vertongen** [comment]
I'm pretty sure it will work with start and end date, I don't see any objections not to implement this feature. 
As you mention yourself, I also think it is connected to #3. We need a 'load more' functionality to avoid problems when a user would select a period that contains too much data. 
(Also the reason why it is capped to 30 days ATM)

**Comment by lestard** [comment]
Maybe we could also use a cap of i.e 30 or 60 days when the user selects start and end date. We could show a message like "Please select a time range of max {X} days" or something if the range is to big.

**Comment by vertongen** [comment]
For the user that might be frustrating if they selected a certain date range and then get a warning. 
In my opinion, we should end up with one of the following:
- cap the selection immediately in the date picker (so they can't select more than 30 days) 
- add load more functionality

But it doesn't mean that it needs to be there from the beginning ;)

**Comment by vertongen** [comment]
The load more functionality is available now and it can handle any range of dates.
It calls the method `activity.getNextPageWithActivities` which accepts a startdate and enddate. This can be passed from the UI.

**Comment by lestard** [comment]
The feature to load next activities when scrolling to the bottom is great. I think this is really sufficient as it's also quite fast so for me personally there is no need for a "startdate" and "enddate" anymore.

**Comment by vertongen** [comment]
Okay, then I'll close this issue for now.
